image: docker:stable

stages:
  - build
  - test
  - deploy

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: "git.crynton.com:49153"

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY

build:
  stage: build
  script:
    - docker build -t typo3 .

# todo: add better tests
test-container:
  stage: test
  script:
    - docker run typo3 php -v
    - docker run typo3 convert -version
    - docker run typo3 composer -V

push-to-registry:
  stage: deploy
  script:
    - docker tag typo3 $DOCKER_REGISTRY/docker/typo3
    - docker push $DOCKER_REGISTRY/docker/typo3

push-on-github:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git remote add github git@github.com:pascal20997/docker-typo3.git
    - git push github master
