image: docker:stable

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  script:
  - docker build -t typo3 .
  - docker tag typo3 git.crynton.com:49153/docker/typo3
  - docker push git.crynton.com:49153/docker/typo3

# todo: add tests
