image: docker:stable

stages:
  - build
  - test
  - release

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: docker-registry.crynton.com
  CONTAINER_TEST_IMAGE: docker-registry.crynton.com/docker/typo3:commit-$CI_COMMIT_SHA
  CONTAINER_LATEST_IMAGE: docker-registry.crynton.com/docker/typo3:latest
  CONTAINER_TAGGED_IMAGE: docker-registry.crynton.com/docker/typo3:$CI_COMMIT_REF_SLUG

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY 

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

# todo: add better tests
test-php:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE php -v

test-composer:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE composer -V

test-imagemagick:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE convert -version

release-latest:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_LATEST_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE

release-tagged:
  stage: release
  script:
    - docker pull $CONTAINER_LATEST_IMAGE
    - docker tag $CONTAINER_LATEST_IMAGE $CONTAINER_TAGGED_IMAGE
    - docker push $CONTAINER_TAGGED_IMAGE
  only:
    - branches
    - tags
  except:
    - master

# Automated docker build will be fired after push!
push-on-github:
  image: buildpack-deps:latest
  stage: release
  # we don´t need docker login for this
  before_script: []
  script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git config --global user.name "Crynton Runner"
    - git config --global user.email "info@crynton.com"
    - git push --mirror git@github.com:pascal20997/docker-typo3.git
